### ISSUE TITLE
Font-issues after expo eject

### ISSUE THREAD

**Issue by rajdeepsharma17** [creativetimofficial/ct-argon-pro-react-native#3]
I have recently bought the Argon pro react-native template and tried ejecting expo so as to get better support for Firebase. But soon as I `expo eject` Fonts aren't loading properly. I understand the fact that switching to react-native cli would cause problems anywhere expo is imported.
But I fixed almost all of the issues including _Expo Apploading_ but when it comes to fonts it doesn't seems to work. 

I tried the same on free version of Argon Native and after commenting out `import { AppLoading } from 'expo';` and also from return statement it works fine.

To resolve the issue I followed this article https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/ and added all the fonts in xcodeproject Resources group
and in info.plist. I have tried every other suggestions given on this link: https://stackoverflow.com/questions/42410354/unrecognized-font-family-on-ios-simulator-with-react-native as well.

# Expected Behavior

The app should work fine even after ejecting from expo.

# Current Behavior
<img width="569" alt="Screenshot 2019-12-19 at 7 31 28 PM" src="https://user-images.githubusercontent.com/30743961/71179440-2b975c00-2296-11ea-95df-07248267578e.png">

My App.js look like this:
```javascript
import React from 'react';
import { Image } from 'react-native';
// import { AppLoading } from 'expo';
import * as Font from 'expo-font';
import { Asset } from 'expo-asset';
import { Block, GalioProvider } from 'galio-framework';

import Screens from './navigation/Screens';
import { Images, articles, argonTheme } from './constants';

// cache app images
const assetImages = [
  Images.Onboarding,
  Images.LogoOnboarding,
  Images.Logo,
  Images.Pro,
  Images.ArgonLogo,
  Images.iOSLogo,
  Images.androidLogo,
];

// cache product images
articles.map(article => assetImages.push(article.image));

function cacheImages(images) {
  return images.map(image => {
    if (typeof image === 'string') {
      return Image.prefetch(image);
    } else {
      return Asset.fromModule(image).downloadAsync();
    }
  });
}

export default class App extends React.Component {
     state = {
     isLoadingComplete: false,
     fontLoaded: false,
   }

  async componentDidMount() {
    Font.loadAsync({
      'open-sans-regular': require('./assets/font/OpenSans-Regular.ttf'),
      'open-sans-light': require('./assets/font/OpenSans-Light.ttf'),
      'open-sans-bold': require('./assets/font/OpenSans-Bold.ttf')
    });

    this.setState({ fontLoaded: true });
  }
  
  render() {
    // if(!this.state.isLoadingComplete) {
    //   return (
    //     <AppLoading
    //       startAsync={this._loadResourcesAsync}
    //       onError={this._handleLoadingError}
    //       onFinish={this._handleFinishLoading}
    //     />
    //   );
    // } else {
      return (
        <GalioProvider theme={argonTheme}>
          <Block flex>
            <Screens />
          </Block>
        </GalioProvider>
      );
    // }
  }

  _loadResourcesAsync = async () => {
    return Promise.all([
      ...cacheImages(assetImages),
    ]);
  };

  _handleLoadingError = error => {
    // In this case, you might want to report the error to your error
    // reporting service, for example Sentry
    console.warn(error);
  };

  _handleFinishLoading = () => {
    if(this.state.fontLoaded) {
      this.setState({ isLoadingComplete: true });
    }
  };

}

```

Please note that it works on Argon react native (Free version), importing expo-assets and expo-fonts doesn't create any problems.

## Steps to Reproduce

```bash
git clone ...
npm i
expo eject
cd ios
pod install 
#Comment out expo imports use code above for reference
npm run ios
```

Also, I do understand it might not be a bug but rather a mistake on my end, so if following the above steps does work for you, please share. Thanks!

**Comment by palingheorghe** [comment]
Hi @rajdeepsharma17 ! Thank you for your interest in our products! 

As far as I can see you're still using `expo-font` for importing your fonts inside the `App.js` file. Reading from their README I got the following line: 'For bare React Native projects, you must ensure that you have installed and configured the react-native-unimodules package before continuing.' Clicking on the `react-native-unimodules` takes us to [this](https://github.com/unimodules/react-native-unimodules) repo. Try and configure everything as written there. I hope this could help you out with your problem.

Thanks,
Alin 🧜🏽‍♂️

**Comment by Namec** [comment]
after all, do you applied a lot of changes or not ?

i am trying to use also RN CLI that can handle some packages.

best
