### ISSUE TITLE
Font.loadAsync error

### ISSUE THREAD

**Issue by deepti-nucleusteq** [creativetimofficial/ct-argon-pro-react-native#7]
You started loading the font "open-sans-regular", but used it before it finished loading.

- You need to wait for Font.loadAsync to complete before using the font.

- We recommend loading all fonts before rendering the app, and rendering only Expo.AppLoading while waiting for loading to complete.
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/expo-font/build/Font.js:18:16 in processFontFamily
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:3683:38 in diffProperties
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:3557:6 in addNestedProperty
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:3694:8 in diffProperties
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:4109:29 in createInstance
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:15835:12 in completeWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19409:28 in completeUnitOfWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19380:30 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19347:39 in workLoopSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18997:22 in renderRoot
* [native code]:null in renderRoot
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18709:28 in runRootCallback
* [native code]:null in runRootCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules/scheduler/cjs/scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18556:30 in scheduleUpdateOnFiber
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:7799:17 in classComponentUpdater.enqueueSetState
- node_modules/react/cjs/react.development.js:325:31 in Component.prototype.setState
- node_modules/redux-persist/es/integration/react.js:60:15 in _defineProperty$argument_2
- node_modules/redux/lib/redux.js:227:10 in dispatch
* http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:143915:23 in rehydrate
- node_modules/redux-persist/lib/persistReducer.js:72:22 in _rehydrate
- node_modules/redux-persist/lib/persistReducer.js:101:16 in getStoredState.then$argument_0
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

**Comment by deepti-nucleusteq** [comment]
I found that if I comment out this line articles.map(article => assetImages.push(article.image)); from App.js it starts throwing this error. Could you please check and let me know how do I remove those un-necessary download of images to my app.

**Comment by harizinside** [comment]
![photo_2020-07-26_22-45-53](https://user-images.githubusercontent.com/13973506/88483394-c75a1a80-cf91-11ea-912a-31aa3b5afcc6.jpg)

I'm getting that too, is any update fix for that?

**Comment by fredericwatteyne** [comment]
I have resolved this by refactoring the code a bit. 

`import React from 'react';
import { Image } from 'react-native';
import { AppLoading } from 'expo';
import * as Font from 'expo-font';
import { Asset } from 'expo-asset';
import { Block, GalioProvider } from 'galio-framework';
import { NavigationContainer } from '@react-navigation/native';

// Before rendering any navigation stack
import { enableScreens } from 'react-native-screens';
enableScreens();

import Screens from './navigation/Screens';
import { Images, articles, argonTheme } from './constants';

// cache app images
const assetImages = [
  Images.Onboarding,
  Images.LogoOnboarding,
  Images.Logo,
  Images.Pro,
  Images.ArgonLogo,
  Images.iOSLogo,
  Images.androidLogo,
];


// cache product images
articles.map(article => assetImages.push(article.image));

function cacheImages(images) {
  return images.map(image => {
    if (typeof image === 'string') {
      return Image.prefetch(image);
    } else {
      return Asset.fromModule(image).downloadAsync();
    }
  });
}

export default class App extends React.Component {
  state = {
    fontLoaded: false,
  }

  async componentDidMount() {
    Font.loadAsync({
      'open-sans-regular': require('./assets/font/OpenSans-Regular.ttf'),
      'open-sans-light': require('./assets/font/OpenSans-Light.ttf'),
      'open-sans-bold': require('./assets/font/OpenSans-Bold.ttf'),
    }).then(response => {
      this.setState({ fontLoaded: true });
    });
  }
  
  render() {
    if(!this.state.fontLoaded) {
      return (
        <AppLoading
          startAsync={this._loadResourcesAsync}
          onError={this._handleLoadingError}
          onFinish={this._handleFinishLoading}
        />
      );
    } else {
      return (
        <NavigationContainer>
          <GalioProvider theme={argonTheme}>
            <Block flex>
              <Screens />
            </Block>
          </GalioProvider>
        </NavigationContainer>
      );
    }
  }

  _loadResourcesAsync = async () => {
    return Promise.all([
      ...cacheImages(assetImages),
    ]);
  };

  _handleLoadingError = error => {
    // In this case, you might want to report the error to your error
    // reporting service, for example Sentry
    console.warn(error);
  };

  _handleFinishLoading = () => {
    //
  };

}
`

**Comment by Brandonjgs** [comment]
> I have resolved this issue by changing the code.
> 
> **The state was not updated correctly so I simplified this by only using "fontLoaded".**
> 
> ```
> import React from 'react';
> import { Image } from 'react-native';
> import { AppLoading } from 'expo';
> import * as Font from 'expo-font';
> import { Asset } from 'expo-asset';
> import { Block, GalioProvider } from 'galio-framework';
> import { NavigationContainer } from '@react-navigation/native';
> 
> // Before rendering any navigation stack
> import { enableScreens } from 'react-native-screens';
> enableScreens();
> 
> import Screens from './navigation/Screens';
> import { Images, articles, argonTheme } from './constants';
> 
> // cache app images
> const assetImages = [
>   Images.Onboarding,
>   Images.LogoOnboarding,
>   Images.Logo,
>   Images.Pro,
>   Images.ArgonLogo,
>   Images.iOSLogo,
>   Images.androidLogo,
> ];
> 
> 
> // cache product images
> articles.map(article => assetImages.push(article.image));
> 
> function cacheImages(images) {
>   return images.map(image => {
>     if (typeof image === 'string') {
>       return Image.prefetch(image);
>     } else {
>       return Asset.fromModule(image).downloadAsync();
>     }
>   });
> }
> 
> export default class App extends React.Component {
>   state = {
>     fontLoaded: false,
>   }
> 
>   async componentDidMount() {
>     Font.loadAsync({
>       'open-sans-regular': require('./assets/font/OpenSans-Regular.ttf'),
>       'open-sans-light': require('./assets/font/OpenSans-Light.ttf'),
>       'open-sans-bold': require('./assets/font/OpenSans-Bold.ttf'),
>     }).then(response => {
>       this.setState({ fontLoaded: true });
>     });
>   }
>   
>   render() {
>     if(!this.state.fontLoaded) {
>       return (
>         <AppLoading
>           startAsync={this._loadResourcesAsync}
>           onError={this._handleLoadingError}
>           onFinish={this._handleFinishLoading}
>         />
>       );
>     } else {
>       return (
>         <NavigationContainer>
>           <GalioProvider theme={argonTheme}>
>             <Block flex>
>               <Screens />
>             </Block>
>           </GalioProvider>
>         </NavigationContainer>
>       );
>     }
>   }
> 
>   _loadResourcesAsync = async () => {
>     return Promise.all([
>       ...cacheImages(assetImages),
>     ]);
>   };
> 
>   _handleLoadingError = error => {
>     // In this case, you might want to report the error to your error
>     // reporting service, for example Sentry
>     console.warn(error);
>   };
> 
>   _handleFinishLoading = () => {
>     //
>   };
> 
> }
> ```

It works for me, thanks.
